services:
  app-be:
    image: irlebedev/nodejs2022q2-service-nest-app:dev
    container_name: nest-app
    build:
      context: .
      dockerfile: app-be.Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - app-db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
  app-db:
    image: irlebedev/nodejs2022q2-service-postgres:latest
    container_name: postgres
    build:
      context: .
      dockerfile: app-db.Dockerfile
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
